src/account/models.py
from flask_login import UserMixin
from src.utils.extensions import db
from src.models import DbMixin
import jwt
import datetime
from datetime import timedelta
from ..utils.config import settings

class Account(UserMixin, DbMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True) 
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    name = db.Column(db.String(1000), nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    is_confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)
    mirror = db.relationship('Mirror', backref='account', cascade="all, delete") 

    def get_reset_token(self):
        delta = timedelta(hours=1)
        now = datetime.datetime.now().astimezone()
        expires = now + delta
        return jwt.encode(
            {
            "exp": expires.timestamp(), 
            "nbf": now,
            "sub": "Password reset",
            "email": self.email,
            },
        key=settings["SECRET_KEY"],
        algorithm="HS256",
    )

src/models.py
from src.utils.extensions import db


class DbMixin(object):
    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

src/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_mail import Mail 
from .utils.config import settings
from .utils.extensions import db
from .account.models import Account
from apscheduler.triggers.interval import IntervalTrigger
from .utils.decorators import scheduler
from flask_wtf.csrf import CSRFProtect
from .mirrors.utils import (
    remove_unused_accounts,
    check_unsync_mirrors,
    validate_branches,
    check_offline_mirrors,
    populate_master_state,
    whitelist_email
    )

app = Flask(__name__)
app.config.update(settings)  

migrate = Migrate(app, db)
mail = Mail(app)
mail.init_app(app)
db.init_app(app)

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

csrf = CSRFProtect()
csrf.init_app(app)

from .auth.routes import auth as auth_blueprint
app.register_blueprint(auth_blueprint)

from .main import main as main_blueprint
app.register_blueprint(main_blueprint)

from .mirrors.routes import mirror as mirror_blueprint
app.register_blueprint(mirror_blueprint)

from .account.routes import account as account_blueprint
app.register_blueprint(account_blueprint)

@login_manager.user_loader
def load_user(user_id):
    return Account.query.get(int(user_id))

@scheduler.scheduled_job(IntervalTrigger(
        minutes=settings["CHECK_BRANCHES_MINUTES"]))
def check_branches():
    with app.app_context():
        populate_master_state()
        validate_branches()

@scheduler.scheduled_job(IntervalTrigger(
        hours=settings["CHECK_OFFLINE_MIRRORS_HOURS"]))
def check_down_state():
    with app.app_context():
        check_offline_mirrors()
        remove_unused_accounts()

@scheduler.scheduled_job(IntervalTrigger(
        hours=settings["CHECK_UNSYNC_MIRRORS_HOURS"]))
def check_out_of_sync_mirrors():
    with app.app_context():
        check_unsync_mirrors()

@scheduler.scheduled_job(IntervalTrigger(
        weeks=settings["WEEKLY_EMAILS"]))
def email_weekly():
    with app.app_context():
        whitelist_email()

scheduler.start()

src/account/routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_required, current_user
from src.utils.extensions import db
from src.account.models import Account
from datetime import datetime
from src.account.token import confirm_token, generate_token
from src.utils import email
from .token import verify_reset_token
from werkzeug.security import generate_password_hash


account = Blueprint("account", __name__)

@account.route('/account')
@login_required
def user_account():
    return render_template('account.html', account=current_user)

@account.route('/account', methods=['POST'])
@login_required
def account_post():
    account_id = request.form.get('account_id')
    delete_account = request.form.get('delete-account')
    if delete_account:
        acc = Account.query.get(account_id)
        acc.delete()
        flash(f'Account Deleted, good bye.')
        return redirect(url_for('main.index'))

@account.route("/confirm/<token>")
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash("Account already confirmed.", "success")
        return redirect(url_for("mirror.my_mirrors"))
    email = confirm_token(token)
    user = Account.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.now()
        user.save()
        flash("You have confirmed your account. Thanks!")
        return redirect(url_for("mirror.my_mirrors"))
    else:
        flash("The confirmation link is invalid or has expired.", "error")
    return redirect(url_for("account.user_account"))

@account.route("/password-reset/<token>", methods=['GET'])
def reset_password(token):
    user = verify_reset_token(token)
    if user:
        return render_template("password_reset.html", token=token)
    return redirect(url_for("auth.login"))

@account.route("/password-reset/<token>", methods=['POST'])
def reset_password_post(token):
    user = verify_reset_token(token)    
    new_password = request.form.get('new_password')
    password_confirm = request.form.get('confirm_password')
    if new_password and password_confirm  and new_password == password_confirm and " " not in new_password:
        user.password = generate_password_hash(new_password)
        user.save()
        flash("Your new password was saved")
    else:
        flash("Your password fields do not match or have empty spaces", "warning")
        return render_template("password_reset.html", token=token)
    
    return redirect(url_for("auth.login"))

@account.route("/resend")
@login_required
def resend_confirmation():
    if not current_user.is_confirmed:        
        token = generate_token(current_user.email)
        confirm_url = url_for("account.confirm_email", token=token, _external=True)
        html = render_template("confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        email.send_email(current_user.email, subject, html)
        flash("A new confirmation email has been sent.")
        return redirect(url_for("account.user_account"))

src/main.py
from flask import Blueprint, render_template, request
from .mirrors.models import Mirror

main = Blueprint("main", __name__)

@main.route("/" , methods=['GET', 'POST'])
def index():
    mirrors = Mirror().query.filter_by(active=True).order_by(Mirror.country).all()
    select = request.form.get('arch-select')

    return render_template(
        'index.html',
        mirrors=mirrors,
        total=len(mirrors),
        select=select
        )

src/mirrors/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from src.mirrors.models import Mirror
from src.utils.extensions import db
from flask_login import current_user, login_required
from flask import make_response
from src.utils.decorators import check_is_confirmed
from src.utils.config import settings
from src.mirrors.utils import test_country, sanitize_url
import json

mirror = Blueprint("mirror", __name__)

def _iter_mirrors():
    query = Mirror().query.filter_by(active=True).all()
    mirrors = []
    for mirror in query:
        country = mirror.country.replace(" ", "_")
        if "russian" in country:
            country = "russia"

        template = {
        "country": country,
        "url": mirror.address,
        "protocols": mirror.protocols(),
        "branches": [],
        "speed": mirror.speed,
        "last_sync": f"{mirror.last_sync_date()} {mirror.last_sync_time()}",
        "score": mirror.points           
        }
        
        if not mirror.stable_in_sync():
            template["branches"].append(0)
        else:
            template["branches"].append(1)
        
        if not mirror.testing_in_sync():
            template["branches"].append(0)
        else:
            template["branches"].append(1)

        if not mirror.unstable_in_sync():
            template["branches"].append(0)
        else:
            template["branches"].append(1)
            
        if not mirror.arm_stable_in_sync():
            template["branches"].append(0)
        else:
            template["branches"].append(1)
        
        if not mirror.arm_testing_in_sync():
            template["branches"].append(0)
        else:
            template["branches"].append(1)

        if not mirror.arm_unstable_in_sync():
            template["branches"].append(0)
        else:
            template["branches"].append(1)            
        
        mirrors.append(template)

    response = make_response(
        json.dumps(mirrors)
        )
    response.headers["Content-Type"] = "application/json"
    response.status_code = 200
    return response
    
@mirror.route("/status.json")
def status():
    response =_iter_mirrors()
    return response

@mirror.route("/mirrors")
@login_required
@check_is_confirmed
def my_mirrors():
    return render_template('mirrors.html', mirrors=current_user.mirror)

@mirror.route("/mirrors/rsync")
@login_required
@check_is_confirmed
def rsync_mirrors():
    query = Mirror().query.filter_by(rsync=True).all()
    mirrors = []
    master = settings["MASTER_RSYNC"]
    for mirror in query:
        if mirror.address != master:
            mirrors.append(mirror)
    
    return render_template('rsync.html', mirrors=mirrors, total=len(mirrors), master=master)

@mirror.route('/mirrors', methods=['POST'])
@login_required
@check_is_confirmed
def mirror_post():
    mirror_id = request.form.get('mirror-id')
    mirror_validation_token = request.form.get('validate-mirror')
    if mirror_validation_token:
        from src.mirrors.utils import validate_ownership
        mirror = Mirror.query.get(mirror_id)

        is_valid = validate_ownership(mirror.get_protocol(), mirror.address, mirror_validation_token)
        if is_valid:
            mirror.account_id = current_user.id
            mirror.save()
            flash(f'Mirror has been added to you account')
            return redirect(url_for('mirror.my_mirrors'))
        else:
            flash(f'File not found, mirror validation failed', "warning")
            return render_template('mirror_exists.html', mirror=mirror, file_name=mirror_validation_token)
    else:
        if mirror_id:
            delete_mirror = request.form.get(f'delete-mirror-{mirror_id}')
            active = request.form.get('active')
            mirror = Mirror.query.get(mirror_id)

            if delete_mirror:
                mirror.delete()
                flash(f'Mirror Deleted')
                return redirect(url_for('mirror.my_mirrors'))

            if active and mirror_id:
                mirror.active = True
                mirror.user_notified = False
                mirror.save()
                flash(f'Mirror Enabled')
                return redirect(url_for('mirror.my_mirrors'))

            elif not active and mirror_id:
                mirror.active = False
                mirror.save()
                flash(f'Mirror Disabled', "warning")
                return redirect(url_for('mirror.my_mirrors'))
            
        else:    
            address = request.form.get('mirror')
            country = request.form.get('country').lower()    
            from src.mirrors.utils import state_check
            address = sanitize_url(address)

            if not address:
                flash('Please insert a mirror address', "error")
                return redirect(url_for('mirror.my_mirrors'))

            address_exists = Mirror.query.filter_by(address=address).first()
            if address_exists:
                import secrets
                token = secrets.token_hex(8)
                return render_template('mirror_exists.html', mirror=address_exists, file_name=token)
            
            protocols = {
                "http": False,
                "https": False,
                "rsync": False
            }
            
            for protocol in protocols:
                if "http" in protocol:
                    server = state_check(protocol, address)
                    if server["state_file_exists"]:
                        protocols[protocol] = server["state_file_exists"]
                        ip = server["ip"]
                else:
                    from src.mirrors.utils import test_rsync
                    rsync = test_rsync(address)
                    if rsync:
                        protocols["rsync"] = rsync
                    

            if any(val == True for val in protocols.values()):
                pass
            else:
                flash('Something is wrong, or server does not exist', "error")
                return redirect(url_for('mirror.my_mirrors'))
                                                   
            db.session.add(
                Mirror(
                address=sanitize_url(address),
                account_id=current_user.id,
                country=test_country(country),
                rsync=protocols["rsync"],
                active=True,
                http=protocols["http"],
                https=protocols["https"],
                speed = server["access_time"],
                ip_whitelist=ip
                )
            )
            
            db.session.commit()           
            flash('Thank you, mirrors are updated', "success")       
            return redirect(url_for('mirror.my_mirrors'))

src/templates/account.html
{% extends "base.html" %}

{% block content %}
<div class="w-full max-w-screen-sm mx-auto -mt-24 self-center">
  <div class="card bg-base-100 shadow-xl py-2 px-4 grid grid-cols-1 gap-2">
      <h3 class="text-xl font-bold">My Account</h3>
      <div class="text-center">Email: {{ account.email }}</div>
      <div class="text-center">Name: {{ account.name }}</div>
      <form method="POST" action="/account" class="grid grid-cols-1 gap-2 mt-2">
        <div class="flex items-center gap-1">
          <input type="checkbox" id="delete-modal" class="modal-toggle" />
          <div class="modal">
            <div class="modal-box bg-base-content text-neutral shadow">
              <h3 class="font-bold text-lg">This action is irreversible.</h3>
              <p class="py-4">You are about to delete your account and mirror data, this cannot be undone, are you sure?</p>
              <div class="modal-action">
                <script>
                  function deleteAccount(el) {
                    el.parentElement.querySelector("#delete-account").checked = true
                    el.parentElement.parentElement.parentElement.parentElement.parentElement.submit()
                  }
                </script>
                <label for="delete-modal" class="btn btn-accent btn-sm shadow">Cancel</label>
                <label for="delete-account" class="btn btn-error btn-sm shadow" onclick="deleteAccount(this)">Delete</label>
                <input name="delete-account" class="hidden" id="delete-account" type="checkbox"/>
                <input name="account_id" type="text" class="hidden" value="{{ account.id }}"/>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              </div>
            </div>
          </div>
        </div>
      </form>
      <div class="text-right mt-4 mb-2">
        {% if not account.is_confirmed %}
        <a href="{{ url_for('account.resend_confirmation') }}" class="btn btn-success py-2 btn-sm mr-2">Resend</a>
        {% endif %}
        <label for="delete-modal" class="btn btn-error py-2 btn-sm">Delete Account</label>
  </div>
</div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html data-theme="forest" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="Mirror Manager | Manjaro"/>
    <meta name="description" content="Mirror manager, a tool for mirror providers to administer their own public mirrors for the Manjaro Linux operating system" />
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#00695c">
    <link rel="icon" type="image/svg+xml" href="/static/img/favicon.svg">
    <link rel="icon" type="image/png" href="/static/img/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mirror Manager | Manjaro</title>
    <link href="/static/styles.css" rel="stylesheet" type="text/css" />
</head>

<body class="bg-gray-50 pb-4">   
<div class="navbar max-w-screen-lg mx-auto rounded-b-xl pt-0">
  <div class="bg-white rounded-b-xl h-[82px]">
    <a href="https://manjaro.org" class="text-gray-900">
      <img class="w-[72px]" src="/static/img/block-logo.svg" alt="manjaro logo">
    </a>
  </div>
    <div class="flex-1 text-center">
      <a href="{{ url_for('main.index') }}" class="ml-4 btn btn-ghost normal-case text-xl cursor-pointer text-gray-900 hover:bg-secondary">Mirror Manager</a>
    </div>
    <div class="flex-none">
        <ul class="menu menu-horizontal px-1">
          {% if not current_user.is_authenticated %}
          <li>
                <a href="{{ url_for('auth.login') }}" class="text-gray-900 hover:bg-secondary">
                    Login
                </a>
          </li>
          <li>
                <a href="{{ url_for('auth.signup') }}" class="text-gray-900 hover:bg-secondary">
                    Sign Up
                </a>
          </li>
          {% endif %}
        </ul>
      </div>
      {% if current_user.is_authenticated %}
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full text-gray-800">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 96 960 960" fill="currentColor"><path d="M222 801q63-40 124.5-60.5T480 720q72 0 134 20.5T739 801q44-54 62.5-109T820 576q0-145-97.5-242.5T480 236q-145 0-242.5 97.5T140 576q0 61 19 116t63 109Zm257.814-195Q422 606 382.5 566.314q-39.5-39.686-39.5-97.5t39.686-97.314q39.686-39.5 97.5-39.5t97.314 39.686q39.5 39.686 39.5 97.5T577.314 566.5q-39.686 39.5-97.5 39.5Zm-.219 370q-83.146 0-156.275-31.5t-127.225-86Q142 804 111 731.159 80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.5q-54 54.5-127.129 86T479.595 976Z"/></svg>
          </div>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-content text-neutral rounded-box w-52 z-10">
          <li>
            <a class="hover:bg-secondary hover:shadow" href="{{ url_for('account.user_account') }}">
                My Account
            </a>
          </li>
          <li>
            <a class="hover:bg-secondary hover:shadow" href="{{ url_for('mirror.my_mirrors') }}">
                My Mirrors
            </a>
          </li>
          <li>
            <a class="hover:bg-secondary hover:shadow" href="{{ url_for('mirror.rsync_mirrors') }}">
                Rsync Mirrors
            </a>
          </li>
          <li>
            <a class="hover:bg-secondary hover:shadow" href="{{ url_for('auth.logout') }}">
                Logout
            </a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
  </div>
    <section class="h-full flex justify-center">
        <div class="flex w-full min-h-[100vh]">
               {% block content %}
               {% endblock %}
        </div>
    </section>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="transition-opacity duration-700 opacity-100 ease-in-out z-10 absolute w-full top-0 right-2 max-w-[350px] mx-auto alert {% if messages[0][0] == 'error' %}alert-error{% elif messages[0][0] == 'warning' %}alert-warning{% elif messages[0][0] == 'info' %}alert-info{% else %}alert-success{% endif %} shadow-lg my-2">
                <div>
                    {% if messages[0][0] == 'error' %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    {% elif messages[0][0] == 'warning' %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                    {% elif messages[0][0] == 'info' %}
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>                    {% endif %}
                  <span>{{ messages[0][1] }}</span>
                </div>
              </div>
            <script>
              let alert = document.querySelector(".alert")
              setTimeout(
                function () {
                  alert.classList.add("opacity-0")
                  setTimeout(
                    function () {
                      alert.classList.add("hidden")
                    }, 3000)
                }, 3000)
            </script>
        {% endif %}
    {% endwith %}
</body>
</html>

src/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="-mt-24 mx-auto self-center">
    <div class="card w-96 bg-base-100 shadow-xl py-2 px-4">
        <h3 class="text-xl font-bold">Login</h3>
        <p class="text-center py-4 text-lg">Manage your mirrors</p>
            <form method="POST" action="/login" class="grid grid-cols-1 gap-4">
                <input name="email" type="email" placeholder="Your Email" class="input input-bordered input-success w-full" autofocus=""/>
                <input name="password" type="password" placeholder="Your Password" class="input input-bordered input-success w-full" />
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="form-control">
                    <label class="label cursor-pointer">
                      <span class="label-text">Remember me</span> 
                      <input name="remember" type="checkbox" checked="checked" class="checkbox checkbox-success" />
                    </label>
                  </div>
                  <button class="btn btn-success mb-2">Login</button>
                <div class="grid grid-row-1 gap-4 justify-center justify-items-center w-full">
                  <button id="passRecoverBtn" class="mb-2 hover:underline">Recover Password</button>
                  <input id="recover" name="recover" type="checkbox" class="hidden" />
                </div>
        </form>
    </div>
</div>
<script>
    let btn = document.querySelector("#passRecoverBtn")
    btn.onclick = function (ev) {
      let recover = document.querySelector("#recover")
      recover.checked = true  
      console.log(revover, btn, ev)   
    }
</script>
{% endblock %}

src/templates/mirror_exists.html
{% extends "base.html" %}

{% block content %}
<div class="w-full max-w-screen-sm mx-auto -mt-24 self-center">
  <div class="card bg-base-100 shadow-xl py-2 px-4 grid grid-cols-1 gap-2">
      <p class="font-bold">This mirror already exists, if you would like to claim it, create a file named "{{ mirror.address }}{{ file_name }}" in your server and validate it.</p>
  
  <form method="POST" action="/mirrors">
    <label for="validate-mirror" class="w-fit mx-auto btn btn-success btn-sm shadow float-right"  onclick="this.parentElement.submit()">Validate</label>
    <input type="hidden" name="validate-mirror" value="{{ file_name }}"/>
    <input type="hidden" name="mirror-id" value="{{ mirror.id }}"/>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  </form>
  </div>
</div>
{% endblock %}

src/templates/mirrors.html
{% extends "base.html" %}

{% block content %}
<div class="w-full max-w-screen-lg mx-auto mt-8">
    <div class="card bg-base-100 shadow-xl py-2 px-4">
        <input type="checkbox" id="add-modal" class="modal-toggle" />
        <div class="modal">
        <div class="modal-box bg-base-content text-neutral">
            <h2 class="pb-4 text-center text-lg ca">Add a Mirror</h2>
            <p class="text-xs mb-4">Make sure your server has directory listing active and files can be reached by Manjaro mirror bot.</p>
            <form method="POST" action="/mirrors" class="grid grid-cols-1 gap-4">
                <input name="mirror" type="text" placeholder="Mirror Address" class="input bg-white text-neutral focus:bg-primary-content w-full" autofocus=""/>
                <input name="country" type="text" placeholder="Country" class="input bg-white text-neutral focus:bg-primary-content w-full" autofocus=""/>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="modal-action">
                    <label for="add-modal" class="btn btn-accent btn-sm shadow">Cancel</label>
                    <button class="btn btn-success btn-sm shadow">Add</button>
                </div>
            </form>
        </div>
        </div>
    
        <div class="text-right py-2">
          <h3 class="text-xl font-bold float-left">My Mirrors</h3>
          <label for="add-modal" class="btn btn-success py-2 btn-sm float-right">add mirror</label>
      </div>
        {% if mirrors %}
            {% for mirror in mirrors %}
            <form method="POST" action="/mirrors" class="grid grid-cols-1 gap-2 mt-2">
              <div class="flex items-center gap-1">
                <span class="label-text w-full">{{ mirror.address }}</span> 
                  <span class="w-full flex gap-3">
                    <span class="pt-[2px]">{{ mirror.speed }}ms</span>
                    {% if mirror.http %}
                      <a target="blank" href="http://{{ mirror.address }}" class="underline">http</a>
                    {% endif %}
                    {% if mirror.https %}
                      <a  target="blank" href="https://{{ mirror.address }}" class="underline">https</a>
                    {% endif %}
                    {% if mirror.rsync %}
                    <a  target="blank" href="rsync://{{ mirror.address }}" class="underline">rsync</a>
                    {% endif %}
                    <span class="pt-[2px]">{{ mirror.ip_whitelist }}</span>
                  </span>
                  <label class="cursor-pointer label" onclick="disableMirror(this)">
                      <input name="active" type="checkbox" class="toggle toggle-success" {% if mirror.active %}checked{% endif %} />
                      <input name="mirror-id" type="text" class="hidden" value="{{ mirror.id }}"/>
                  </label>
                  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <label for="delete-modal-{{ mirror.id }}" class="btn btn-error btn-xs ml-2 relative shadow">Delete</label>
                <input type="checkbox" id="delete-modal-{{ mirror.id }}" class="modal-toggle" />
                <div class="modal">
                  <div class="modal-box bg-base-content text-neutral shadow">
                    <h3 class="font-bold text-lg">This action is irreversible.</h3>
                    <p class="py-4">You are about to delete "{{ mirror.address }}" this cannot be undone, are you sure?</p>
                    <div class="modal-action">
                      <label for="delete-modal-{{ mirror.id }}" class="btn btn-accent btn-sm shadow">Cancel</label>
                      <label for="delete-mirror-{{ mirror.id }}" class="btn btn-error btn-sm shadow" onclick="deleteMirror(this, '{{ mirror.id }}')">Delete</label>
                      <input name="delete-mirror-{{ mirror.id }}" class="hidden" id="delete-mirror-{{ mirror.id }}" type="checkbox"/>
                    </div>
                  </div>
                </div>
              </div>
            </form>
            {% endfor %}
            {% else %}
              <p>No mirrors yet</p>
            {% endif %}
</div>
<script>
  function deleteMirror(el, id) {
    let mirror = document.querySelector(`#delete-mirror-${id}`).checked = true
    el.parentElement.parentElement.parentElement.parentElement.parentElement.submit()
  }
  function disableMirror(el) {
    setTimeout(function() {
      el.parentElement.parentElement.submit()
    }, 250)
  }
</script>
{% endblock %}